services:
  postgres:
    image: postgres:ru_RU.utf8
    build: ./Postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: NSTUChatbot
      POSTGRES_PASSWORD: NSTUChatbot
      POSTGRES_DB: NSTUChatbotDatabase

  dbapi:
    image: dbapi:latest
    environment:
      migrateOnStartup: "true"
      NLU_HOST: nlu
      NLU_PORT: "5005"
      NLU_CONFIG_FILE: nlu_config.yml
    depends_on:
      - postgres
      - nlu
    env_file:
      - .env
    build: ./Database
    ports:
      - 5005:8000

  nlu:
    image: diploma_rasa_project
    build: ./NLU
    volumes:
      - nlu:/app/NLU/models
    environment:
      RASA_TELEMETRY_ENABLED: "false"
      APP_FOLDER: /app/NLU
      DATA_FOLDER: data
      MODELS_FOLDER: models
      SPELLING_ARCHIVE_FILE: dialogues.zip
      SPELLING_ALPHABET_FILE: alhabet_ru.txt
      SPELLING_DATASET_FILE: dialogues.txt
      SPELLING_MODEL_FILE: ru_nstu_chatbot.bin
    ports:
      - "5005"

  chatbot:
    image: chatbot
    build: ./tgbot_v2
    env_file:
      - .env
    depends_on:
      - dbapi
    environment:
      DB_API_HOST: http://dbapi:8000
      NSTU_API_HOST: https://api.ciu.nstu.ru

volumes:
  pgdata:
  nlu:
