language: ru

pipeline:
  - name: text_preprocessing.TextPreprocessor
  - name: spelling_correction.SpellingCorrector
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3
  - name: DIETClassifier
    epochs: 300
  - name: FallbackClassifier
    threshold: 0.9

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.9

rules:
  - rule: fallback
    steps:
      - intent: nlu_fallback
      - action: action_two_stage_fallback
      - active_loop: action_two_stage_fallback

responses:
  utter_please_rephrase:
    - text: Простите, не понял ваш вопрос. Пожалуйста, попробуйте его переформулировать.
  utter_default:
    - text: Простите, ничем не могу помочь. Попробуйте задать вопрос напрямую членам приёмной комисии нажав на соответствующую кнопку.
